### ISSUE TITLE
Wrong openurl generated with sciencedirect PII

### ISSUE THREAD

**Issue by kerphi** [istex/istex-browser-addon#4]
J'ai constaté des trucs étranges dans la console JS avec l'appel des PII.
sur cette page : http://www.sciencedirect.com/science/article/pii/S0301008209001439

On a des appels étranges de ce type (j'ai pris un PII qui est dans ISTEX dans cet exemple) : 
https://api.istex.fr/document/openurl?rft_id=info:pii//pii/S0171-9335%2898%2980118-0&noredirect

Alors que l'openurl appelée comme ceci fonctionne : 
https://api.istex.fr/document/openurl?rft_id=info:piii/S0171-9335%2898%2980118-0&noredirect

![image](https://cloud.githubusercontent.com/assets/328244/18687793/fcc45cb2-7f81-11e6-8a84-733d8b7f6c5e.png)

**Comment by kermitt2** [comment]
Bien vu ! Je corrige… à noter qu'un formattage des PII est également nécessaire dans l'API ISTEX, je l'ai notifié à l'équipe API.

Ceci marche bien : 
https://api.istex.fr/document/openurl?rft_id=info:pii/0168-583X(91)95215-Y&noredirect=true 
{
  "resourceUrl": "https://api.istex.fr/document/82266FE7A5A9E9B5152E7F5434A1FD2E557D4783/fulltext/pdf",
  "_message": "Nous avons identifié la ressource que vous recherchez."
}

Mais pas cela pour le moment :
https://api.istex.fr/document/openurl?rft_id=info:pii/0168583X9195215Y&noredirect=true
{
  "code": 404,
  "_message": "Nous ne possédons pas cette ressources.",
  "_comment": "Si vous avez saisi un DOI, assurez-vous qu'il s'agît du DOI du document (article ou chapitre), et non pas de son contenant (livre ou revue)."
}

**Comment by kerphi** [comment]
Fixed in 26ed5a0037877281b6a65958c89eff09905ff236
